annonces_annonce:
    resource: "@AnnoncesBundle/Resources/config/routing/annonce.yml"
    prefix:   /annonce

annonces_categorie:
    resource: "@AnnoncesBundle/Resources/config/routing/categorie.yml"
    prefix:   /categorie

annonces_homepage:
    path:     /
    defaults: { _controller: AnnoncesBundle:Default:index }

search:
    path:     annonce/search
    defaults: { _controller: AnnoncesBundle:Recherche:search }

mes_annonces:
    path:     annonce/mesannonces
    defaults: { _controller: AnnoncesBundle:Recherche:mesAnnonces }
