annonces_annonce:
    resource: "@AnnoncesBundle/Resources/config/routing/annonce.yml"
    prefix:   /annonce

annonces_categorie:
    resource: "@AnnoncesBundle/Resources/config/routing/categorie.yml"
    prefix:   /categorie

annonces_homepage:
    path:     /
    defaults: { _controller: AnnoncesBundle:Default:index }

mes_annonces:
    path:     /annonce/mesAnnonces
    defaults: { _controller: AnnoncesBundle:MesAnnonces:mesAnnonces }

search:
    path:     /search
    defaults: { _controller: AnnoncesBundle:Recherche:search }

recherche:
    path:     /recherche
    defaults: { _controller: AnnoncesBundle:Map:recherche }
