departement_index:
    path:     /
    defaults: { _controller: "LocalisationBundle:Departement:index" }
    methods:  GET

departement_show:
    path:     /{id}/show
    defaults: { _controller: "LocalisationBundle:Departement:show" }
    methods:  GET

departement_new:
    path:     /new
    defaults: { _controller: "LocalisationBundle:Departement:new" }
    methods:  [GET, POST]

departement_edit:
    path:     /{id}/edit
    defaults: { _controller: "LocalisationBundle:Departement:edit" }
    methods:  [GET, POST]

departement_delete:
    path:     /{id}/delete
    defaults: { _controller: "LocalisationBundle:Departement:delete" }
    methods:  DELETE
